### ISSUE TITLE
todo-list example broken on iOS & Android

### ISSUE THREAD

**Issue by fluidpixel** [GeekyAnts/nativebase-docs#129]
**Describe the bug**
Trying to preview the basic todo-list app on a device, results in a broken experience, with most of the content unviewable

**To Reproduce**
Open the todo-list example https://docs.nativebase.io/todo-example
Preview on a device, either within the webpage (iOS or Android), or a physical device (only iOS tested)

**Expected behavior**
The application displays within the screen

**Screenshots**
<img width="787" alt="Screen Shot 2021-10-28 at 2 19 55 pm" src="https://user-images.githubusercontent.com/733214/139186323-33c8dee5-99c3-42f2-8721-2d96a81efc32.png">

**Device (please complete the following information):**
 Safari 14.1 or iOS 15

**Comment by flexbox** [comment]
Hey @fluidpixel 

Thanks for your contribution 🚀
I am gardening the opened PR's and I feel the problem is solved.

![IMG_8828FF90230A-1](https://user-images.githubusercontent.com/360936/182164129-4f5ee5c1-e331-4f22-85fa-c708160d723c.jpeg)

Tested on iOS 15
