### ISSUE TITLE
Close Popover

### ISSUE THREAD

**Issue by ushyDev** [GeekyAnts/nativebase-docs#130]
How can i close Popover without using Popover.CloseButton?

**Comment by flexbox** [comment]
Hey @ushyDev 

Thanks for your contribution 🚀

I had the problem as you and it's well explained here
https://stackoverflow.com/questions/73034809/how-can-i-close-a-popover-programatically-with-native-base

I am gardening the opened PR's and I have a feeling the problem is solved.
