### ISSUE TITLE
Responsive example not working in safari mobile

### ISSUE THREAD

**Issue by IHIutch** [GeekyAnts/nativebase-docs#2]
Content is all there, looks like a height issue. Probably how safari uses flex or 100% heights.

![image](https://user-images.githubusercontent.com/20825047/125324232-b96de880-e30d-11eb-91f2-f536b529bf01.png)

**Comment by Ajamuar** [comment]
Hi @IHIutch, we are looking into this issue and we hope to fix this ASAP.

**Comment by flexbox** [comment]
Hey @IHIutch 

Thanks for your contribution 🚀
I am gardening the opened PR's and I have a feeling the problem is solved.

Tested on Safari 
![2022-08-01 15 49 57](https://user-images.githubusercontent.com/360936/182162894-e352fc71-60bd-45b4-9938-f7eaa1bbfab9.gif)

**Comment by IHIutch** [comment]
Seems to be working for me as well. Excited about how this library is progressing!
