### ISSUE TITLE
SwipeList example broken on ios devices

### ISSUE THREAD

**Issue by armincerf** [GeekyAnts/nativebase-docs#24]
**Describe the bug**

**To Reproduce**
Run this example on an ios device https://docs.nativebase.io/buildingSwipeList

**Expected behavior**
The same as you see on the Web tab.

**Smartphone (please complete the following information):**
iPhone 12
iOS 14.5

Also ios and android tabs in expo go don't work

**Additional context**

Can be sort of fixed by wrapping the Avatar text in a Text component, but still doesn't show Text to the right of it (see screenshot)
![image](https://user-images.githubusercontent.com/9809256/126880128-5c1a2c03-d351-4fae-8936-a343b02a13fc.png)

**Comment by flexbox** [comment]
Hey @armincerf

Thanks for your contribution 🚀
I am gardening the opened PR's and I have a feeling the problem is solved.

![IMG_185B652400ED-1](https://user-images.githubusercontent.com/360936/182163814-65f337dd-bf40-4616-b6a7-0ec890cb89b9.jpeg)

Tested on iOS 15+
